# Generated by Django 4.0.2 on 2022-03-15 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registraion_model',
            name='phonenumber',
            field=models.CharField(max_length=10),
        ),
    ]
